### ISSUE TITLE
Describe or Automate Kubify Cluster Reboot

### ISSUE THREAD

**Issue by vlerenc** [gardener/kubify#50]
Under certain circumstances (technical issues in the infrastructure), a Kubify cluster may "lose coherence" and must be "rebootet" (bootstrapped via the bootstrap control plane). This is neither automated nor described (unlike the [https://github.com/gardener/kubify#cluster-recovery](recovery), which is the last resort if everything breaks). It would be good to do either, please.

**Comment by afritzler** [comment]
With 2d4e099cdf39ce00fef52389a06f8f366174d26b a troubleshooting guide has been added to the docs of kubify.

**Comment by afritzler** [comment]
With 2a8ac9268e6c83b0c817441bb3dda943f655571e we introduced an automatic CP recovery via the bootstrap controlplane.
