### ISSUE TITLE
Documentation issue on page "https://github.com/gardener/kubify/blob/master/README.md"

### ISSUE THREAD

**Issue by freegroup** [gardener/kubify#54]
please add the *kubify* logo on top of this page. good example is https://github.com/gardener/gardenctl

![logo_kubify 2x](https://user-images.githubusercontent.com/1155039/43255369-ee6dc602-90c9-11e8-8c2a-da96fabf131f.png)

---
Page: [https://github.com/gardener/kubify/blob/master/README.md](https://github.com/gardener/kubify/blob/master/README.md)
don't remove the link to the page. It's required for the processor

**Comment by afritzler** [comment]
Done!
