### ISSUE TITLE
Error while running deploy kubify 

### ISSUE THREAD

**Issue by nikhilsap** [gardener/kubify#68]
We are trying to update Gardener to latest version. We have deployed Gardener using [this method](https://github.com/gardener/landscape-setup)

When i run  `deploy  kubify`, i am facing this error 

`Error: module.instance.module.iaas.module.bastion.data.aws_ami.image: "owners": required field is not set
`
`Error: module.instance.module.master.module.vms.data.aws_ami.image: "owners": required field is not set
`
`
Error: module.instance.module.worker.module.vms.data.aws_ami.image: "owners": required field is not set
`

Any idea what might be causing this?

**Comment by afritzler** [comment]
This issues has been fixed #70
